sudo: required
services:
    - docker

before_install:
    - docker build -t docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true docker-react npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-045581390716"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY